# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Utiliser une image de base Debian ou Ubuntu
FROM ubuntu:latest

# Installer les mises à jour et FileZilla Server
RUN apt-get update && \
    apt-get install -y filezilla && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Exposer le port par défaut de FileZilla Server
EXPOSE 21

# Commande pour démarrer FileZilla Server (remplacez cette commande avec la commande appropriée pour démarrer le serveur)
CMD ["filezilla-server"]
